### ISSUE TITLE
Consistent use of exceptions

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/django-appsettings#55]
- `AppSettings.check` method expects any type of exceptions and raises them all at once as `ImproperlyConfigured`
- `Setting.run_validators` method expects and raises `ValidationError`
- `Setting.check` method expects `ValidationError` and raises `ValueError`
- `NestedDictSetting.check` method expects and raises `ValidationError`
- `NestedListSetting.check` should be the same as `NestedDictSetting`

It seems the ugly duckling is the original `Setting.check` method, which should raise a `ValidationError` as well. Checkers are deprecated so other type of exceptions should not appear anymore.

**Comment by ziima** [comment]
Since #80, the `check` raises `ImproperlyConfigured`. I think, exceptions are now consistent enough.

**Comment by pawamoy** [comment]
Thanks @ziima
