### ISSUE TITLE
Modernize packaging (with poetry)

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/django-appsettings#58]
I'd like to modernize the packaging of the app a bit, using [poetry](https://github.com/sdispater/poetry) for example.

I would typically regenerate the project with this cookiecutter of mine: [cookie-poetry](https://github.com/pawamoy/cookie-poetry).

It's not something I would do immediately though, just posting this here to get feedback. Also the cookiecutter is not integrated with tox, so maybe I would just add poetry manually.

Of course I'd like to know if my two most valuable contributors, @stinovlas and @ziima have anything against that!

We can discuss this here, if you have any questions, just ask :slightly_smiling_face:

**Comment by stinovlas** [comment]
I use [pipenv](https://github.com/pypa/pipenv) for some of my projects, not for libraries though. `poetry` seems to be more general, so it might handle library nicely as well. I think I'll try it out, it seems like an interesting alternative.

**Comment by pawamoy** [comment]
I tried both, and I absolutely prefer poetry :smile: ! You should definitely try it out :slightly_smiling_face:

**Comment by ziima** [comment]
Will the installation via `pip` still work? Although I'm looking forward to the standardized `pyproject.toml`, I consider the compatibility with `pip` still crucial at this moment.

**Comment by pawamoy** [comment]
Yes it will still work with `pip`. I currently have several projects published with `poetry`, you can try to install them to see if it works for you! `aria2p`, `shellhistory`, `git-changelog`, `privibot`

**Comment by stinovlas** [comment]
I recently spent some time playing with poetry and I like it a lot. There are some issues, that makes it difficult to incorporate to some of our projects, the main one being that we are adding custom build steps to our `setup.py` for compiling translations, transpiling JavaScript, building grpc modules and so on. This seems to be complicated with `pyproject.toml` and we currently don't have any viable replacement. But still, poetry seems very nice (especially the upcoming stable release) and I'll probably try to incorporate it to our projects as soon as it will be viable.

**Comment by ziima** [comment]
I tried one of the above mentioned projects and it works fine. Though, it probably requires to maintain both the `setup.py` and `pyproject.toml`.

**Comment by pawamoy** [comment]
Yes, poetry might not be flexible enough for some projects.

But in any case, publishing django-appsettings through poetry should not be a problem for you as you can still list it as a dependency in a project using setup.py/setup.cfg/requirements.txt.

**Comment by ziima** [comment]
Yes, that should be fine.

**Comment by pawamoy** [comment]
I'm now using [PDM](https://github.com/pdm-project/pdm) instead of Poetry. However I don't think I'll update this project so I'll close this issue. Let me know if you'd like me to transfer the repo to another account.
