### ISSUE TITLE
Raise ImproperlyConfigured on invalid setting

### ISSUE THREAD

**Issue by ziima** [pawamoy/django-appsettings#67]
It seems, appsettings produce various exceptions on errors. To denote errors in settings correctly the `ImproperlyConfigured` should be raised instead.

**Comment by pawamoy** [comment]
I quickly looked at the code but I'm not sure what you mean. It seems everything is caught by `AppSettings.check` and re-raised as a single `ImproperlyConfigured` exception.

Then `AttributeError` can be raised when trying to access a required setting that was not declared, but it seems to make sense? It should already have been caught at Django startup anyway?

**Comment by ziima** [comment]
You're right. I forgot about `AppSettings`. I only checked the `Setting` classes themselves.

**Comment by ziima** [comment]
How about we raised `ImproperlyConfigured` directly from `Setting.check`. I don't think it's worth raising `AttributeError` and `ValueError` in there.

**Comment by pawamoy** [comment]
I think it makes sense yes. `Setting.check` is exactly used for that, to check if the setting is configured properly :slightly_smiling_face:
