### ISSUE TITLE
check-setup stalls tox locally

### ISSUE THREAD

**Issue by ziima** [pawamoy/django-appsettings#78]
The `check-setup` job stalls my tox on desktop. Is anybody having similar issue?

**Comment by pawamoy** [comment]
Working fine on latest master on my end!

**Comment by ziima** [comment]
If I clean the git repo, it stalls on
```
Getting credentials from keyring for https://pypi.org/simple
```
when I run it again, it passes. But it only happens on my work computer, so it may be a network issue.

**Comment by pawamoy** [comment]
From my experience, stalls like that are because you're not passing through the corporate proxy. I set the `HTTP_PROXY, `HTTPS_PROXY` and `NO_PROXY` environment variables at work. My 2 cents.
