### ISSUE TITLE
Deprecate support for environment variables?

### ISSUE THREAD

**Issue by ziima** [pawamoy/django-appsettings#98]
As we move our projects to docker and we use environment variables more often to configure projects, we learned following

 1. There is a whole project python-environ, https://github.com/pjialin/django-environ, which handles environment variables for any Django application and Django itself, not only application based on django-appsettings.
 2. Combination of python-environ and django-appsettings causes confusion, because direct access to environment variable in django-appsettings takes precedence over any usage of `Environ` in settings, ignoring any modification of the value which happens there.

Hence, I suggest to deprecate the processing of environment variables and support usage of `python-environ` to handle them. `django-appsettings` would then focus on handling the application settings based on values provided by the Django settings object, regardless on their origin.

**Comment by fenryxo** [comment]
The appsetting's support for environment variables leads to hard-to-investigate deployment failures, so it would be great to have a way to switch it off.

**Comment by thclark** [comment]
I thoroughly agree with @jiri-janousek. Really enjoying this library overall (frankly, I think it should be part of django core) but this definitely creates some very weird edge cases where values you set using some logic in `settings.py` that then get overridden and can be a nightmare to track down.

**Comment by pawamoy** [comment]
I'm not using this app anymore so @ziima, @stinovlas, feel free to deprecate support for environment variables. Or someone else can a PR. Shouldn't be too hard :slightly_smiling_face: A simple deprecation warning somewhere, and next time removal of the feature.

**Comment by stinovlas** [comment]
I believe we agreed to do this. Since we are still on zero-based versions, breaking changes should be introduced in minor version (the next one being `0.8`). We can publish patch version `0.7.2` with the deprecation warning and then `0.8` with the feature removed. I don't think that I or @ziima can tend to this right away, but we might get to it in several weeks. In the meantime, PR is always welcome :slightly_smiling_face:.

**Comment by stinovlas** [comment]
I whipped up a quick PR for the deprecation itself. As for the actual removal, we'll probably resolve it in another issue.
